### ISSUE TITLE
Does not recognize any toolchains when used on Travis ci

### ISSUE THREAD

**Issue by Ewpratten** [wpilibsuite/GradleRIO#145] opened 2018-09-06 11:09 UTC
For some reason, when using gradlerio on Travis ci for testing code, gradlerio does not find the FRC toolchain, but it works fine on other ci services (like circle ci) 

The error message is just the: "you do not have any compatible toolchains installed, please run <install commands> to install one"

**Comment by JacisNonsense** [comment] 2018-09-06 12:11
Run with `--info` and send us the output. A link to your travis ci yml script would also be useful so we can ensure it's installed properly

Note that it won't work with the 2019 beta toolchain

**Comment by Ewpratten** [comment] 2018-09-06 13:43
Ah. I forgot to mention that I am using the 2019 beta.

**Comment by JacisNonsense** [comment] 2018-09-07 01:48
I'm closing this since it's a duplicate of #143

**Closed by JacisNonsense** 2018-09-07 01:48 UTC
